import cv2
import numpy as n
img =cv2.imread('df.jpg')
normal_blur=cv2.blur(img,(5,5),)
cv2.imshow('Original',img)
cv2.waitKey(0)
cv2.imshow('Normal Blur',normal_blur)
cv2.waitKey(0)
gaussian_blur=cv2.GaussianBlur(img,(5,5),0)
cv2.imshow('Gaussian Blur',gaussian_blur)
cv2.waitKey(0)
Median_blur=cv2.medianBlur(img,5)
cv2.imshow('Median blur',Median_blur)
cv2.waitKey(0)
bilateral_blur=cv2.bilateralFilter(img,7,50,50)
cv2.imshow('Bilateral blur',bilateral_blur)
cv2.imwrite('df12.jpg',img)
cv2.waitKey(0)
cv2.destroyAllWindows()